// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using ProjectNetIa.Infrastructure.Data;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260714063842_AddProductImageUrl")]
    partial class AddProductImageUrl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProjectNetIa.Domain.Entities.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("HexCode")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HexCode = "#000000",
                            IsActive = true,
                            Name = "Negro"
                        },
                        new
                        {
                            Id = 2,
                            HexCode = "#FFFFFF",
                            IsActive = true,
                            Name = "Blanco"
                        },
                        new
                        {
                            Id = 3,
                            HexCode = "#0000FF",
                            IsActive = true,
                            Name = "Azul"
                        },
                        new
                        {
                            Id = 4,
                            HexCode = "#FF0000",
                            IsActive = true,
                            Name = "Rojo"
                        },
                        new
                        {
                            Id = 5,
                            HexCode = "#008000",
                            IsActive = true,
                            Name = "Verde"
                        },
                        new
                        {
                            Id = 6,
                            HexCode = "#F5F5DC",
                            IsActive = true,
                            Name = "Beige"
                        },
                        new
                        {
                            Id = 7,
                            HexCode = "#808080",
                            IsActive = true,
                            Name = "Gris"
                        });
                });

            modelBuilder.Entity("ProjectNetIa.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CustomerDocumentTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerDocumentTypeId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("ProjectNetIa.Domain.Entities.CustomerDocumentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CustomerDocumentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "CC"
                        },
                        new
                        {
                            Id = 2,
                            Name = "CE"
                        },
                        new
                        {
                            Id = 3,
                            Name = "NIT"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Passport"
                        });
                });

            modelBuilder.Entity("ProjectNetIa.Domain.Entities.Inventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("MinimumQuantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProductVariantId")
                        .IsUnique();

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("ProjectNetIa.Domain.Entities.InventoryMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("InventoryMovementTypeId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InventoryMovementTypeId");

                    b.HasIndex("ProductVariantId");

                    b.ToTable("InventoryMovements");
                });

            modelBuilder.Entity("ProjectNetIa.Domain.Entities.InventoryMovementType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("InventoryMovementTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "InitialStock"
                        },
                        new
                        {
                            Id = 2,
                            Name = "ManualAdjustment"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sale"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Return"
                        });
                });

            modelBuilder.Entity("ProjectNetIa.Domain.Entities.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("InvoiceStatusId")
                        .HasColumnType("integer");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique();

                    b.HasIndex("InvoiceStatusId");

                    b.HasIndex("SaleId")
                        .IsUnique();

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("ProjectNetIa.Domain.Entities.InvoiceStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("InvoiceStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Issued"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Cancelled"
                        });
                });

            modelBuilder.Entity("ProjectNetIa.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(256)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("ProductCategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("ProductCategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ProjectNetIa.Domain.Entities.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Camisetas y tops casuales",
                            IsActive = true,
                            Name = "Camisetas"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Camisas formales e informales",
                            IsActive = true,
                            Name = "Camisas"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Pantalones de uso diario",
                            IsActive = true,
                            Name = "Pantalones"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Jeans y prendas denim",
                            IsActive = true,
                            Name = "Jeans"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Chaquetas y prendas exteriores",
                            IsActive = true,
                            Name = "Chaquetas"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Vestidos y enterizos",
                            IsActive = true,
                            Name = "Vestidos"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Calzado",
                            IsActive = true,
                            Name = "Zapatos"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Complementos y accesorios",
                            IsActive = true,
                            Name = "Accesorios"
                        });
                });

            modelBuilder.Entity("ProjectNetIa.Domain.Entities.ProductVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ColorId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("SizeId")
                        .HasColumnType("integer");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.HasIndex("SizeId");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.HasIndex("ProductId", "SizeId", "ColorId")
                        .IsUnique();

                    b.ToTable("ProductVariants");
                });

            modelBuilder.Entity("ProjectNetIa.Domain.Entities.Sale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<int>("SaleOriginId")
                        .HasColumnType("integer");

                    b.Property<int>("SaleStatusId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("SaleOriginId");

                    b.HasIndex("SaleStatusId");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("ProjectNetIa.Domain.Entities.SaleItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductVariantId");

                    b.HasIndex("SaleId");

                    b.ToTable("SaleItems");
                });

            modelBuilder.Entity("ProjectNetIa.Domain.Entities.SaleOrigin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SaleOrigins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Manual"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Chatbot"
                        });
                });

            modelBuilder.Entity("ProjectNetIa.Domain.Entities.SaleStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SaleStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Completed"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Cancelled"
                        });
                });

            modelBuilder.Entity("ProjectNetIa.Domain.Entities.Size", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Sizes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "XS"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "S"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "M"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "L"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "XL"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Name = "XXL"
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            Name = "36"
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            Name = "37"
                        },
                        new
                        {
                            Id = 9,
                            IsActive = true,
                            Name = "38"
                        },
                        new
                        {
                            Id = 10,
                            IsActive = true,
                            Name = "39"
                        },
                        new
                        {
                            Id = 11,
                            IsActive = true,
                            Name = "40"
                        },
                        new
                        {
                            Id = 12,
                            IsActive = true,
                            Name = "41"
                        },
                        new
                        {
                            Id = 13,
                            IsActive = true,
                            Name = "42"
                        });
                });

            modelBuilder.Entity("ProjectNetIa.Domain.Entities.Customer", b =>
                {
                    b.HasOne("ProjectNetIa.Domain.Entities.CustomerDocumentType", "CustomerDocumentType")
                        .WithMany("Customers")
                        .HasForeignKey("CustomerDocumentTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CustomerDocumentType");
                });

            modelBuilder.Entity("ProjectNetIa.Domain.Entities.Inventory", b =>
                {
                    b.HasOne("ProjectNetIa.Domain.Entities.ProductVariant", "ProductVariant")
                        .WithOne("Inventory")
                        .HasForeignKey("ProjectNetIa.Domain.Entities.Inventory", "ProductVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("ProjectNetIa.Domain.Entities.InventoryMovement", b =>
                {
                    b.HasOne("ProjectNetIa.Domain.Entities.InventoryMovementType", "InventoryMovementType")
                        .WithMany("InventoryMovements")
                        .HasForeignKey("InventoryMovementTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjectNetIa.Domain.Entities.ProductVariant", "ProductVariant")
                        .WithMany("InventoryMovements")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InventoryMovementType");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("ProjectNetIa.Domain.Entities.Invoice", b =>
                {
                    b.HasOne("ProjectNetIa.Domain.Entities.InvoiceStatus", "InvoiceStatus")
                        .WithMany("Invoices")
                        .HasForeignKey("InvoiceStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjectNetIa.Domain.Entities.Sale", "Sale")
                        .WithOne("Invoice")
                        .HasForeignKey("ProjectNetIa.Domain.Entities.Invoice", "SaleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InvoiceStatus");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("ProjectNetIa.Domain.Entities.Product", b =>
                {
                    b.HasOne("ProjectNetIa.Domain.Entities.ProductCategory", "ProductCategory")
                        .WithMany("Products")
                        .HasForeignKey("ProductCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("ProjectNetIa.Domain.Entities.ProductVariant", b =>
                {
                    b.HasOne("ProjectNetIa.Domain.Entities.Color", "Color")
                        .WithMany("ProductVariants")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjectNetIa.Domain.Entities.Product", "Product")
                        .WithMany("ProductVariants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjectNetIa.Domain.Entities.Size", "Size")
                        .WithMany("ProductVariants")
                        .HasForeignKey("SizeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Color");

                    b.Navigation("Product");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("ProjectNetIa.Domain.Entities.Sale", b =>
                {
                    b.HasOne("ProjectNetIa.Domain.Entities.Customer", "Customer")
                        .WithMany("Sales")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProjectNetIa.Domain.Entities.SaleOrigin", "SaleOrigin")
                        .WithMany("Sales")
                        .HasForeignKey("SaleOriginId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjectNetIa.Domain.Entities.SaleStatus", "SaleStatus")
                        .WithMany("Sales")
                        .HasForeignKey("SaleStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("SaleOrigin");

                    b.Navigation("SaleStatus");
                });

            modelBuilder.Entity("ProjectNetIa.Domain.Entities.SaleItem", b =>
                {
                    b.HasOne("ProjectNetIa.Domain.Entities.ProductVariant", "ProductVariant")
                        .WithMany("SaleItems")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjectNetIa.Domain.Entities.Sale", "Sale")
                        .WithMany("Items")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductVariant");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("ProjectNetIa.Domain.Entities.Color", b =>
                {
                    b.Navigation("ProductVariants");
                });

            modelBuilder.Entity("ProjectNetIa.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("ProjectNetIa.Domain.Entities.CustomerDocumentType", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("ProjectNetIa.Domain.Entities.InventoryMovementType", b =>
                {
                    b.Navigation("InventoryMovements");
                });

            modelBuilder.Entity("ProjectNetIa.Domain.Entities.InvoiceStatus", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("ProjectNetIa.Domain.Entities.Product", b =>
                {
                    b.Navigation("ProductVariants");
                });

            modelBuilder.Entity("ProjectNetIa.Domain.Entities.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ProjectNetIa.Domain.Entities.ProductVariant", b =>
                {
                    b.Navigation("Inventory");

                    b.Navigation("InventoryMovements");

                    b.Navigation("SaleItems");
                });

            modelBuilder.Entity("ProjectNetIa.Domain.Entities.Sale", b =>
                {
                    b.Navigation("Invoice");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("ProjectNetIa.Domain.Entities.SaleOrigin", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("ProjectNetIa.Domain.Entities.SaleStatus", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("ProjectNetIa.Domain.Entities.Size", b =>
                {
                    b.Navigation("ProductVariants");
                });
#pragma warning restore 612, 618
        }
    }
}
